joint_names: [  "wam/base_yaw_joint", 
                "wam/shoulder_pitch_joint", 
                "wam/shoulder_yaw_joint", 
                "wam/elbow_pitch_joint", 
                "wam/wrist_yaw_joint", 
                "wam/wrist_pitch_joint", 
                "wam/palm_yaw_joint",
                # "wam/bhand/finger_1/prox_joint",
                # "wam/bhand/finger_1/med_joint",
                # "wam/bhand/finger_1/dist_joint",
                # "wam/bhand/finger_2/prox_joint",
                # "wam/bhand/finger_2/med_joint",
                # "wam/bhand/finger_2/dist_joint",
                # "wam/bhand/finger_3/med_joint",
                # "wam/bhand/finger_3/dist_joint",
                ]