# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: ARL
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - wam/base_yaw_joint
    - wam/shoulder_pitch_joint
    - wam/shoulder_yaw_joint
    - wam/elbow_pitch_joint
    - wam/wrist_yaw_joint
    - wam/wrist_pitch_joint
    - wam/palm_yaw_joint
    - wam/bhand/finger_1/prox_joint
    - wam/bhand/finger_1/med_joint
    - wam/bhand/finger_1/dist_joint
    - wam/bhand/finger_2/prox_joint
    - wam/bhand/finger_2/med_joint
    - wam/bhand/finger_2/dist_joint
    - wam/bhand/finger_3/med_joint
    - wam/bhand/finger_3/dist_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - wam/base_yaw_joint
    - wam/shoulder_pitch_joint
    - wam/shoulder_yaw_joint
    - wam/elbow_pitch_joint
    - wam/wrist_yaw_joint
    - wam/wrist_pitch_joint
    - wam/palm_yaw_joint
  gains:
    wam/base_yaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wam/shoulder_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wam/shoulder_yaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wam/elbow_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wam/wrist_yaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wam/wrist_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wam/palm_yaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1